#library(Seurat)
#library(data.table)
#source("https://bioconductor.org/biocLite.R")
#biocLite('BiocManager')
#BiocManager::install("biomaRt", suppressUpdates = TRUE)
#library(biomaRt)

t4 <- as.data.frame(fread('t_4k_matrix.csv'))
t3 <- as.data.frame(fread('t_3k_matrix.csv'))

genes <- t4$V1
mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
G_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id","external_gene_name"),values=genes,mart= mart)
G_list <- as.data.table(G_list)
genes <- as.data.table(genes)
genes <- merge(genes, G_list, all=T, by.x="genes", by.y="ensembl_gene_id")
genes <- na.omit(genes)
t4 <- merge(t4, genes, by.x='V1', by.y='genes', all=T)
t4 <- na.omit(t4)
t4 <- as.data.table(t4)
t4 <- t4[,c(4540, 2:4539)]
t4 <- t4[!duplicated(t4[,c(external_gene_name)] ),]
fwrite(t4, 't_4k_genesymbol.csv', sep='\t', col.names = T, row.names = F, quote=F)
t4 <- as.data.frame(fread('t_4k_genesymbol.csv'))
t4 <- as.data.frame(t4)
row.names(t4) <- t4$external_gene_name
t4 <- t4[1:33201, 2:4539]
t4 <- CreateSeuratObject(raw.data = t4, project = "t4")
t4@meta.data$sample <- "t4"

mito.genes <- grep(pattern = "^MT-", x = rownames(x = t4@data), value = TRUE)
percent.mito <- Matrix::colSums(t4@raw.data[mito.genes, ])/Matrix::colSums(t4@raw.data)
rpl.genes <- grep(pattern = "^RPL", x = rownames(x = t4@data), value = TRUE)
rps.genes <- grep(pattern = "^RPS", x = rownames(x = t4@data), value = TRUE)
percent.rps <- Matrix::colSums(t4@raw.data[rps.genes, ])/Matrix::colSums(t4@raw.data)
percent.rpl <- Matrix::colSums(t4@raw.data[rpl.genes, ])/Matrix::colSums(t4@raw.data)
t4 <- AddMetaData(object = t4, metadata = percent.mito, col.name = "percent.mito")
t4 <- AddMetaData(object = t4, metadata = percent.rpl, col.name = "percent.rpl")
t4 <- AddMetaData(object = t4, metadata = percent.rps, col.name = "percent.rps")
t4 <- FilterCells(object = t4, subset.names = c("nGene", "percent.mito"), low.thresholds = c(500, 0), high.thresholds = c(3000, 0.2))
t4 <- NormalizeData(t4)
t4 <- ScaleData(t4, display.progress = F, vars.to.regress = c('nUMI'))
t4 <- FindVariableGenes(object = t4, mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.6, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- SetAllIdent(t4, id='res.0.6')
t4 <- RunPCA(object = t4, pcs.print = 1:5, genes.print = 5)
t4 <- RunTSNE(object = t4, dims.use = 1:8, do.fast = TRUE)

t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.1, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.2, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.3, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.4, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.5, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.6, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.7, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.8, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 0.9, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- FindClusters(object = t4, reduction.type = "pca", dims.use = 1:10, resolution = 1, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t4 <- RunPCA(object = t4, pcs.print = 1:5, genes.print = 5)
t4 <- RunTSNE(object = t4, dims.use = 1:8, do.fast = TRUE)
head(t4@meta.data)
t4 <- SetAllIdent(t4, id='res.0.6')
save(t4, file='t4.Seurat.RData')


# t3----
t3 <- as.data.frame(fread('t_3k_matrix.csv'))
genes <- t3$V1
mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
G_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id","external_gene_name"),values=genes,mart= mart)
G_list <- as.data.table(G_list)
genes <- as.data.table(genes)
genes <- merge(genes, G_list, all=T, by.x="genes", by.y="ensembl_gene_id")
genes <- na.omit(genes)
t3 <- merge(t3, genes, by.x='V1', by.y='genes', all=T)
t3 <- na.omit(t3)
t3 <- as.data.table(t3)
t3 <- t3[!duplicated(t3[,c(external_gene_name)] ),]
t3 <- t3[,c(3557, 2:3556)]
fwrite(t3, 't_3k_genesymbol.csv', sep='\t', col.names = T, row.names = F, quote=F)
t3 <- as.data.frame(fread('t_3k_genesymbol.csv'))
t3 <- as.data.frame(t3)
row.names(t3) <- t3$external_gene_name
t3 <- t3[1:33202, 2:3556]
t3 <- CreateSeuratObject(raw.data = t3, project = "t3")
t3@meta.data$sample <- "t3"

mito.genes <- grep(pattern = "^MT-", x = rownames(x = t3@data), value = TRUE)
percent.mito <- Matrix::colSums(t3@raw.data[mito.genes, ])/Matrix::colSums(t3@raw.data)
rpl.genes <- grep(pattern = "^RPL", x = rownames(x = t3@data), value = TRUE)
rps.genes <- grep(pattern = "^RPS", x = rownames(x = t3@data), value = TRUE)
percent.rps <- Matrix::colSums(t3@raw.data[rps.genes, ])/Matrix::colSums(t3@raw.data)
percent.rpl <- Matrix::colSums(t3@raw.data[rpl.genes, ])/Matrix::colSums(t3@raw.data)
t3 <- AddMetaData(object = t3, metadata = percent.mito, col.name = "percent.mito")
t3 <- AddMetaData(object = t3, metadata = percent.rpl, col.name = "percent.rpl")
t3 <- AddMetaData(object = t3, metadata = percent.rps, col.name = "percent.rps")
t3 <- FilterCells(object = t3, subset.names = c("nGene", "percent.mito"), low.thresholds = c(500, 0), high.thresholds = c(3000, 0.2))
t3 <- NormalizeData(t3)
t3 <- ScaleData(t3, display.progress = F, vars.to.regress = c('nUMI'))
t3 <- FindVariableGenes(object = t3, mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.6, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- SetAllIdent(t3, id='res.0.6')
t3 <- RunPCA(object = t3, pcs.print = 1:5, genes.print = 5)
t3 <- RunTSNE(object = t3, dims.use = 1:8, do.fast = TRUE)

t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.1, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.2, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.3, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.4, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.5, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.6, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.7, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.8, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 0.9, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- FindClusters(object = t3, reduction.type = "pca", dims.use = 1:10, resolution = 1, print.output = 0, save.SNN = TRUE, force.recalc=TRUE)
t3 <- RunPCA(object = t3, pcs.print = 1:5, genes.print = 5)
t3 <- RunTSNE(object = t3, dims.use = 1:8, do.fast = TRUE)
head(t3@meta.data)
t3 <- SetAllIdent(t3, id='res.0.6')
save(t3, file='t3.Seurat.RData')
